// put this at top of the file where you create the supabase client
console.log('VITE_SUPABASE_URL ->', import.meta.env.VITE_SUPABASE_URL);
console.log('VITE_SUPABASE_KEY (first 12 chars) ->', import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.slice(0,12));

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});